# FROM curlimages/curl:7.70.0 as download_qemu

# RUN curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz \
#     | tar zxvf - -C . && \
#   mv qemu-3.0.0+resin-arm/qemu-arm-static /usr/local/bin

FROM nginx
COPY qemu-arm-static /usr/bin/
# COPY --from=download_qemu /usr/local/bin/qemu-*-static /usr/bin